### ISSUE TITLE
 IndexError: pop from empty list

### ISSUE THREAD

**Issue by JaimePSantos** [den01-python-programming-exercises/exercise-3-10-index-of-smallest-JaimePSantos#1]
Hello,
I've tried a different couple of implementations but always get the same error:
`FAILED tests/test_exercise.py::test_exercise - IndexError: pop from empty list`
Might have something to do with the test inputs being strings, because my local tests are working as intended, unless im making a less obvious mistake.
Thanks!

**Comment by Scott3142** [comment]
Take a look at this:

```
if(numberStr=="-1"):
    break
intList.append(numberStr)
```

and check the condition in the README file that is supposed to stop the program.  It's not designed to end when `-1` is input. The condition is different for this program.

**Comment by JaimePSantos** [comment]
Oops, autopilot must've kicked in, sorry about that! Thanks!
